// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_XZxZ-SEzUP5IcpPKZ0ykXmiEFqWHo4',
    appId: '1:947086042483:web:369a34e4e0f98a68875106',
    messagingSenderId: '947086042483',
    projectId: 'personalapp-42343',
    authDomain: 'personalapp-42343.firebaseapp.com',
    storageBucket: 'personalapp-42343.firebasestorage.app',
    measurementId: 'G-0PPGGY81QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYFQmDj89lR7j-SHOgDBRTRzjxrcJtxHw',
    appId: '1:947086042483:android:506df9b122739c29875106',
    messagingSenderId: '947086042483',
    projectId: 'personalapp-42343',
    storageBucket: 'personalapp-42343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3UZlY41cYKArOKEcPaJWc1h2v6QYYqA',
    appId: '1:947086042483:ios:34e6b0c583fd9038875106',
    messagingSenderId: '947086042483',
    projectId: 'personalapp-42343',
    storageBucket: 'personalapp-42343.firebasestorage.app',
    iosBundleId: 'com.example.voiceMemoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe3UZlY41cYKArOKEcPaJWc1h2v6QYYqA',
    appId: '1:947086042483:ios:34e6b0c583fd9038875106',
    messagingSenderId: '947086042483',
    projectId: 'personalapp-42343',
    storageBucket: 'personalapp-42343.firebasestorage.app',
    iosBundleId: 'com.example.voiceMemoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_XZxZ-SEzUP5IcpPKZ0ykXmiEFqWHo4',
    appId: '1:947086042483:web:1ceaa2c0a7c7530b875106',
    messagingSenderId: '947086042483',
    projectId: 'personalapp-42343',
    authDomain: 'personalapp-42343.firebaseapp.com',
    storageBucket: 'personalapp-42343.firebasestorage.app',
    measurementId: 'G-5SLG0C6FYR',
  );
}
